### ISSUE TITLE
ungap-btg: Cannot be used if next tile is fully water

### ISSUE THREAD

**Issue by SammySkycrafts** [TheFGFSEagle/fgtools#5]
It appears that ungap-btg cannot be used without erroring if any of the surrounding tiles (N,S,E,W) are 100% water. This is because TerraGear does not produce tiles for an area that is 100% water, like an ocean. TerraSync does not have tiles in these areas either for the same reason.

2 ways I can think of for potential fixes:

- Provide just a warning if there is no tile found for either N,S,E,or W, but do not cause a fatal error.
- Provide a default "fallback" btg with the tools that would be used in the event that any tile is not found. This would be a flat tile, at sea level, so the script can happily interpolate between the existing tile, and sea level.

**Comment by magnetic-eagle** [comment]
Thanks, good idea ! :) Note though that the script pretty much doesn't work right now.

**Comment by SammySkycrafts** [comment]
I saw that. If/When you get it working I'm sure it will be appreciated by many. I know I will certainly get use out of it.

**Comment by magnetic-eagle** [comment]
I'm sure too - we'd finally be able to integrate custom sceneries into TerraSync !

**Comment by magnetic-eagle** [comment]
Small update - I think I got it partly working (the border vertices are now moved to the altitude of the nearest border vertex of the neighbor tile, have not had a chance to test the resulting btg files in-sim yet, though) - I've yet to implement tri splitting, for cases where there is no vertex close enough to avoid seams, and handle water tiles - from which the latter should be the easier one, since it is just an easy check if the BTG file exists ! :D

**Comment by SammySkycrafts** [comment]
Great! I'll give this a try when I get a chance :)

**Comment by magnetic-eagle** [comment]
Should work now ! :) BTW, you can also install this from pip now.

**Comment by SammySkycrafts** [comment]
> Should work now ! :) BTW, you can also install this from pip now.

Cool! And I saw about pip, I personally prefer the way it's fine now, but thanks for telling me!

**Comment by magnetic-eagle** [comment]
Does it work ?

**Comment by SammySkycrafts** [comment]
> Does it work ?

Sorry for the late reply. I've just tried this today, and while the script didn't fail in any way, there are still significant seams in the tile. I'll upload a video of this shortly.

**Comment by SammySkycrafts** [comment]
> > Does it work ?
> 
> Sorry for the late reply. I've just tried this today, and while the script didn't fail in any way, there are still significant seams in the tile. I'll upload a video of this shortly.

https://cdn.discordapp.com/attachments/1067454596575920139/1184227314960191639/lipa.mp4?ex=658b34a1&is=6578bfa1&hm=1225621b4a21d674758a0db3ccc91dfd2c847650905647f0a8a407a479cd1d08&

**Comment by magnetic-eagle** [comment]
Yeah, thanks for the video - that's probably because I haven't implemented any triangle splitting yet - but could you take a screenshot of a seam with a terrain tile directly from TerraGear, and another screenshot from the same viewpoint, same direction after running the script on the tile?

**Comment by SammySkycrafts** [comment]
> Yeah, thanks for the video - that's probably because I haven't implemented any triangle splitting yet - but could you take a screenshot of a seam with a terrain tile directly from TerraGear, and another screenshot from the same viewpoint, same direction after running the script on the tile?

Sure! Ive attached that below, along with a video of the same. As you can see, there is zero difference unfortunately. 
https://cdn.discordapp.com/attachments/838166778727104555/1188604141405216818/fgscenery.mp4?ex=659b20de&is=6588abde&hm=c3ca3034654e06094b7560d62b7ca01ce48631d5dff95680f8e62b11648dde52&

And here are 2 screenshots from the times you requested.

![Before modification](https://github.com/TheFGFSEagle/fgtools/assets/77464976/73e8887c-98af-4467-9bf1-54d9d0e4d001)


![After modification](https://github.com/TheFGFSEagle/fgtools/assets/77464976/a0d4c322-0b0d-4be2-97ad-5d0477d08b99)

**Comment by magnetic-eagle** [comment]
Indeed no change, that is weird …
